easy_admin:
    site_name: 'To-Do-List'
    user:
        name_property_path: 'username'
    list:
        actions:
            - { name: 'edit', icon: 'pencil' }
            - { name: 'delete', icon: 'trash'}
        title: '%%entity_label%% listing'
    design:
        menu:
            - { entity: 'User', icon: 'user'}
            - { entity: 'Todolist', icon: 'list'}
            - { entity: 'Task', icon: 'tasks'}
    entities:
        User:
            class: App\Entity\User
            label: 'Users'
            list:
                fields: ['id','username','roles','todolists']
            disabled_actions: ['new']
            form:
                fields:
                    - 'username'
                    - { property: 'roles', type: 'collection', permission: 'ROLE_SUPER_ADMIN' }
                    - { property: 'todolists', type: 'easyadmin_autocomplete' }

        Todolist:
            class: App\Entity\Todolist
            label: 'To-do-lists'
        Task:
            class: App\Entity\Task
            label: 'Tasks'